Update SW - Browser Extensions
omits FF, probably doesn't need the die() help text if run as EA

diff --git a/SW - Browser Extensions b/SW - Browser Extensions
--- a/SW - Browser Extensions
+++ b/SW - Browser Extensions
@@ -9,32 +9,10 @@ _arg_wysiwygField=$2
 # Determines whether or not help text is necessary and routes the output to stderr
 die() {
     local _ret="${2:-1}"
-    echo "$1" >&2
-    test "${_PRINT_HELP:-no}" = yes && print_help >&2
+    echo "$1" &gt;&amp;2
+    test "${_PRINT_HELP:-no}" = yes &amp;&amp; print_help &gt;&amp;2
     exit "${_ret}"
 }
-
-# Prints the help text
-print_help() {
-    echo "Get the browser extensions for Safari, Chrome, and Edge that are installed on a macOS system."
-    echo "Usage: [multilineCustomFieldName] [wysiwygCustomFieldName]"
-}
-
-# Check if --help or -h is passed as an argument
-for _arg in "$@"; do
-    case "$_arg" in
-    --help | -h)
-        print_help
-        exit 0
-        ;;
-    esac
-done
-
-
-# Warn that if not running as root, the script may not be able to access all user directories
-if [[ $EUID -ne 0 ]]; then
-    echo "[Warn] This script may not be able to access all user directories unless run as root."
-fi
 
 # Converts a string input into an HTML table format
 convertToHTMLTable() {
@@ -46,12 +24,12 @@ convertToHTMLTable() {
         _key="$1"
         case "$_key" in
         --delimiter | -d)
-            test $# -lt 2 && echo "[Error] Missing value for the optional argument" >&2 && return 1
+            test $# -lt 2 &amp;&amp; echo "[Error] Missing value for the optional argument" &gt;&amp;2 &amp;&amp; return 1
             _arg_delimiter=$2
             shift
             ;;
         --*)
-            echo "[Error] Got an unexpected argument" >&2
+            echo "[Error] Got an unexpected argument" &gt;&amp;2
             return 1
             ;;
         *)
@@ -66,26 +44,26 @@ convertToHTMLTable() {
         if [ -p /dev/stdin ]; then
             _arg_inputObject=$(cat)
         else
-            echo "[Error] Missing input object to convert to table" >&2
+            echo "[Error] Missing input object to convert to table" &gt;&amp;2
             return 1
         fi
     fi
 
-    local htmlTable="<table>\n"
+    local htmlTable="&lt;table&gt;\n"
     htmlTable+=$(printf '%b' "$_arg_inputObject" | head -n1 | awk -F "$_arg_delimiter" '{
-    printf "<tr>"
-    for (i=1; i<=NF; i+=1)
-      { printf "<th>"$i"</th>" }
-    printf "</tr>"
+    printf "&lt;tr&gt;"
+    for (i=1; i&lt;=NF; i+=1)
+      { printf "&lt;th&gt;"$i"&lt;/th&gt;" }
+    printf "&lt;/tr&gt;"
     }')
     htmlTable+="\n"
     htmlTable+=$(printf '%b' "$_arg_inputObject" | tail -n +2 | awk -F "$_arg_delimiter" '{
-    printf "<tr>"
-    for (i=1; i<=NF; i+=1)
-      { printf "<td>"$i"</td>" }
-    print "</tr>"
+    printf "&lt;tr&gt;"
+    for (i=1; i&lt;=NF; i+=1)
+      { printf "&lt;td&gt;"$i"&lt;/td&gt;" }
+    print "&lt;/tr&gt;"
     }')
-    htmlTable+="\n</table>"
+    htmlTable+="\n&lt;/table&gt;"
 
     printf '%b' "$htmlTable" '\n'
 }
@@ -95,10 +73,10 @@ createExtList() {
     browser=$2 # chrome or edge
     user_name=$(echo "$userHome" | cut -d "/" -f 3)
     if [[ "${browser}" == "chrome" ]]; then
-        manifests=$(find "${userHome}/Library/Application Support/Google/Chrome" -type f -name 'manifest.json' 2>/dev/null | grep "Extensions")
+        manifests=$(find "${userHome}/Library/Application Support/Google/Chrome" -type f -name 'manifest.json' 2&gt;/dev/null | grep "Extensions")
         profileLocalState="${userHome}/Library/Application Support/Google/Chrome/Local State"
     elif [[ "${browser}" == "edge" ]]; then
-        manifests=$(find "${userHome}/Library/Application Support/Microsoft Edge" -type f -name 'manifest.json' 2>/dev/null | grep "Extensions")
+        manifests=$(find "${userHome}/Library/Application Support/Microsoft Edge" -type f -name 'manifest.json' 2&gt;/dev/null | grep "Extensions")
         profileLocalState="${userHome}/Library/Application Support/Microsoft Edge/Local State"
     fi
 
@@ -134,9 +112,9 @@ createExtList() {
 
         # Get the id of the extension from the manifest path by splitting the path on '/' and getting the 9th element
         if [[ "${browser}" == "chrome" ]]; then
-            extID=$(awk -F '/' '{print $10}' <<<"$manifest")
+            extID=$(awk -F '/' '{print $10}' &lt;&lt;&lt;"$manifest")
         elif [[ "${browser}" == "edge" ]]; then
-            extID=$(awk -F '/' '{print $9}' <<<"$manifest")
+            extID=$(awk -F '/' '{print $9}' &lt;&lt;&lt;"$manifest")
         fi
         # Get name from manifest
         name=$(
@@ -165,9 +143,9 @@ createExtList() {
                         var data = JSON.parse(ObjC.unwrap($.NSString.alloc.initWithDataEncoding($.NSData.dataWithContentsOfFile('$(dirname "$manifest")/$en_messages'), $.NSUTF8StringEncoding)));
                         var searchKey = '$name';
                         var asLowercase = searchKey.toLowerCase();
-                        var name = data[Object.keys(data).find(key => key.toLowerCase() === asLowercase)].message;
+                        var name = data[Object.keys(data).find(key =&gt; key.toLowerCase() === asLowercase)].message;
                         name;
-                    " 2>/dev/null
+                    " 2&gt;/dev/null
                 )
             elif [ -f "$(dirname "$manifest")/$enUS_messages" ]; then
                 # Check if message.json exists in enUS folder
@@ -176,9 +154,9 @@ createExtList() {
                         var data = JSON.parse(ObjC.unwrap($.NSString.alloc.initWithDataEncoding($.NSData.dataWithContentsOfFile('$(dirname "$manifest")/$enUS_messages'), $.NSUTF8StringEncoding)));
                         var searchKey = '$name';
                         var asLowercase = searchKey.toLowerCase();
-                        var name = data[Object.keys(data).find(key => key.toLowerCase() === asLowercase)].message;
+                        var name = data[Object.keys(data).find(key =&gt; key.toLowerCase() === asLowercase)].message;
                         name;
-                    " 2>/dev/null
+                    " 2&gt;/dev/null
                 )
             fi
         fi
@@ -187,13 +165,13 @@ createExtList() {
         else
             printf "%s|%s|%s|%s|%s\n" "$user_name" "$profileName" "Name Not Found" "$extID" "$version"
         fi
-    done <<<"$manifests"
+    done &lt;&lt;&lt;"$manifests"
 }
 
 # Get a list of all users in the /Users directory except Shared
 users=()
 for user in /Users/*; do
-    if [[ -d "$user" && ! "$user" =~ /Users/Shared ]]; then
+    if [[ -d "$user" &amp;&amp; ! "$user" =~ /Users/Shared ]]; then
         users+=("${user##*/}")
     fi
 done
@@ -203,27 +181,27 @@ if [[ ${#users[@]} -eq 0 ]]; then
     _PRINT_HELP=no die "[Error] No user directories found in /Users"
 fi
 
-safari_title="Safari Extensions"
-safari_extensions=""
+# safari_title="Safari Extensions"
+# safari_extensions=""
 chrome_title="Chrome Extensions"
 chrome_extensions=""
 edge_title="Edge Extensions"
 edge_extensions=""
 
 # Safari
-for user in "${users[@]}"; do
-    ext_plist="/Users/$user/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions/Extensions.plist"
-    pattern='(com\..*)\s\((.*)\)'
-    if [[ -f "$ext_plist" ]]; then
-        safari_extensions+=$'\n'"$(
-            grep -Eo "$pattern" "$ext_plist" | while read -r line; do
-                ext_name=$(echo "$line" | awk -F ' ' '{print $1}')
-                ext_id=$(echo "$line" | awk -F ' ' '{print $2}' | tr -d '()')
-                printf "%s|%s|%s\n" "$user" "$ext_name" "$ext_id"
-            done
-        )"
-    fi
-done
+# for user in "${users[@]}"; do
+#     ext_plist="/Users/$user/Library/Containers/com.apple.Safari/Data/Library/Safari/AppExtensions/Extensions.plist"
+#     pattern='(com\..*)\s\((.*)\)'
+#     if [[ -f "$ext_plist" ]]; then
+#         safari_extensions+=$'\n'"$(
+#             grep -Eo "$pattern" "$ext_plist" | while read -r line; do
+#                 ext_name=$(echo "$line" | awk -F ' ' '{print $1}')
+#                 ext_id=$(echo "$line" | awk -F ' ' '{print $2}' | tr -d '()')
+#                 printf "%s|%s|%s\n" "$user" "$ext_name" "$ext_id"
+#             done
+#         )"
+#     fi
+# done
 
 # Chrome
 for user in "${users[@]}"; do
@@ -239,15 +217,15 @@ done
 
 if [[ -n $_arg_multilineField ]] || [[ -n $_arg_wysiwygField ]]; then
     # Add headers if a custom field is set
-    if [[ -n "${safari_extensions}" ]]; then
-        safari_extensions=$(echo -e "User|Name|Id\n$safari_extensions")
-    fi
+    # if [[ -n "${safari_extensions}" ]]; then
+    #    safari_extensions=$(echo -e "User|Name|Id\n$safari_extensions")
+    # fi
     if [[ -n "${chrome_extensions}" ]]; then
         chrome_extensions=$(echo -e "User|Profile Name|Name|Id|Version\n$chrome_extensions")
     fi
-    if [[ -n "${firefox_addons}" ]]; then
-        firefox_addons=$(echo -e "User|Profile Name|Name|Id|Description\n$firefox_addons")
-    fi
+    # if [[ -n "${firefox_addons}" ]]; then
+    #    firefox_addons=$(echo -e "User|Profile Name|Name|Id|Description\n$firefox_addons")
+    # fi
     if [[ -n "${edge_extensions}" ]]; then
         edge_extensions=$(echo -e "User|Profile Name|Name|Id|Version\n$edge_extensions")
     fi
@@ -255,19 +233,9 @@ fi
 
     # Formats the extension data for the multiline custom field
     multilineValue=""
+    
     # Check if any browser extensions were found
-    if [[ -n "$safari_title" ]] && [[ -n "${safari_extensions}" ]]; then
-        multilineValue+=$'\n'
-        multilineValue+="$safari_title:"
-        multilineValue+=$'\n'
-        multilineValue+=$(
-            # Convert the safari_extensions string to a table format. Skip the first line as it is the header
-            echo "$safari_extensions" | tail -n +2 | while IFS='|' read -r user name id; do
-                printf "User: %s, Name: %s, Id: %s\n" "$user" "$name" "$id"
-            done
-        )
-    fi
-    if [[ -n "$chrome_title" ]] && [[ -n "${chrome_extensions}" ]]; then
+    if [[ -n "$chrome_title" ]] &amp;&amp; [[ -n "${chrome_extensions}" ]]; then
         multilineValue+=$'\n'
         multilineValue+="$chrome_title:"
         multilineValue+=$'\n'
@@ -280,20 +248,7 @@ fi
             done
         )
     fi
-    if [[ -n "$firefox_title" ]] && [[ -n "${firefox_addons}" ]]; then
-        multilineValue+=$'\n'
-        multilineValue+="$firefox_title:"
-        multilineValue+=$'\n'
-        multilineValue+=$(
-            # Convert the firefox_addons string to a table format. Skip the first line as it is the header
-            echo "$firefox_addons" | tail -n +2 | while IFS='|' read -r user profileName name id description; do
-                if [[ -n "$name" ]]; then
-                    printf "User: %s, Profile Name: %s, Name: %s, Id: %s, Description: %s\n" "$user" "$profileName" "$name" "$id" "$description"
-                fi
-            done
-        )
-    fi
-    if [[ -n "$edge_title" ]] && [[ -n "${edge_extensions}" ]]; then
+    if [[ -n "$edge_title" ]] &amp;&amp; [[ -n "${edge_extensions}" ]]; then
         multilineValue+=$'\n'
         multilineValue+="$edge_title:"
         multilineValue+=$'\n'
@@ -306,14 +261,15 @@ fi
             done
         )
     fi
+    
     # if all multilineValue is empty, set it to "No browser extensions found"
     if [[ -z "$multilineValue" ]]; then
         multilineValue="No browser extensions found"
     fi
 
     # Tries to set the multiline custom field using ninjarmm-cli and captures the output
-    if ! output=$(printf '%b' "$multilineValue"  set --stdin "$_arg_multilineField" 2>&1); then
-        echo "[Error] $output" >&2
+    if ! output=$(printf '%b' "$multilineValue"  set --stdin "$_arg_multilineField" 2&gt;&amp;1); then
+        echo "[Error] $output" &gt;&amp;2
         EXITCODE=1
     fi
 
@@ -324,55 +280,45 @@ if [[ -n $_arg_wysiwygField ]]; then
     
     # Initializes an HTML formatted string with headers and extension details
     # Check if any browser extensions were found
-    if [[ -n "$safari_title" ]] && [[ -n "${safari_extensions}" ]]; then
-        htmlObject+="<h2>$safari_title</h2>"
-        htmlObject+=$(echo "$safari_extensions" | convertToHTMLTable --delimiter '|')
-    fi
-    if [[ -n "$chrome_title" ]] && [[ -n "${chrome_extensions}" ]]; then
-        htmlObject+="<h2>$chrome_title</h2>"
+    if [[ -n "$chrome_title" ]] &amp;&amp; [[ -n "${chrome_extensions}" ]]; then
+        htmlObject+="&lt;h2&gt;$chrome_title&lt;/h2&gt;"
         htmlObject+=$(echo "$chrome_extensions" | convertToHTMLTable --delimiter '|')
     fi
-    if [[ -n "$edge_title" ]] && [[ -n "${edge_extensions}" ]]; then
-        htmlObject+="<h2>$edge_title</h2>"
+    if [[ -n "$edge_title" ]] &amp;&amp; [[ -n "${edge_extensions}" ]]; then
+        htmlObject+="&lt;h2&gt;$edge_title&lt;/h2&gt;"
         htmlObject+=$(echo "$edge_extensions" | convertToHTMLTable --delimiter '|')
     fi
     # if all htmlObject is empty, set it to "No browser extensions found"
     if [[ -z "$htmlObject" ]]; then
-        htmlObject="<p>No browser extensions found</p>"
+        htmlObject="&lt;p&gt;No browser extensions found&lt;/p&gt;"
     fi
-    # Replace <table> with <table style='white-space:nowrap;'>
-    htmlObject=${htmlObject//<table>/<table style=\'white-space:nowrap;\'>}
+    # Replace &lt;table&gt; with &lt;table style='white-space:nowrap;'&gt;
+    htmlObject=${htmlObject//&lt;table&gt;/&lt;table style=\'white-space:nowrap;\'&gt;}
     # Tries to set the WYSIWYG custom field using ninjarmm-cli and captures the output
-    if ! output=$(printf '%b' "$htmlObject" | set --stdin "$_arg_wysiwygField" 2>&1); then
+    if ! output=$(printf '%b' "$htmlObject" | set --stdin "$_arg_wysiwygField" 2&gt;&amp;1); then
     EXITCODE=1
     fi
 fi
 
 # If both _arg_multilineField and _arg_wysiwygField are not set, or if there is an error saving to the custom fields, print the results
-if [[ -z $_arg_multilineField && -z $_arg_wysiwygField ]] || [[ $EXITCODE -ne 0 ]]; then
-    echo "<result>"
-    echo "$safari_title:"
-    echo "$safari_extensions" | while IFS='|' read -r user name id; do
-        if [[ -n "$name" ]]; then
-            printf "%s %s\n" "$name" "$id"
-        fi
-    done
-    echo ""
+if [[ -z $_arg_multilineField &amp;&amp; -z $_arg_wysiwygField ]] || [[ $EXITCODE -ne 0 ]]; then
+    echo "&lt;result&gt;"
     echo "$chrome_title:"
     echo "$chrome_extensions" | while IFS='|' read -r user profileName name id version; do
         if [[ -n "$name" ]]; then
-            printf "%s %s %s\n" "$name" "$id" "$version"
+            printf "%s, %s, %s\n" "$name" "$id" "$version"
         fi
     done
     echo ""
     echo "$edge_title:"
     echo "$edge_extensions" | while IFS='|' read -r user profileName name id version; do
         if [[ -n "$name" ]]; then
-            printf "%s %s %s\n" "$name" "$id" "$version"
+            printf "%s, %s, %s\n" "$name" "$id" "$version"
         fi
     done
     # If no extensions are found, print a message
-    if [[ -z "$safari_extensions" ]] && [[ -z "$chrome_extensions" ]] && [[ -z "$firefox_addons" ]] && [[ -z "$edge_extensions" ]]; then
-        echo "</result>"
+    if [[ -z "$chrome_extensions" ]] &amp;&amp; [[ -z "$edge_extensions" ]]; then
+        echo "&lt;/result&gt;"
     fi
-fi
+fi</scriptContentsMac>
+</extensionAttribute>
